
AllCops:
  Exclude:
    - "bin/*"
    - "db/**/*"
    - "config/**/*"
    - "Guardfile"
    - "Rakefile"
  DisplayCopNames: true
  DisabledByDefault: true

Metrics/LineLength:
  Enabled: false
  Max: 300
Metrics/MethodLength:
  Enabled: false
  Include: ["app/controllers/*"]
  Max: 2000
Metrics/AbcSize:
  Enabled: false
  Include: ["app/controllers/*"]
  Max: 300
Metrics/ClassLength:
  Enabled: false
  Max: 1500
Naming/MethodParameterName:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/For:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Style/WordArray:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented